import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateNotificationTables1779426877296 implements MigrationInterface {
    name = 'UpdateNotificationTables1779426877296'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_token"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_templates_project_active"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_templates_project_code_channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" ADD "project_name" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_templates"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" ADD "channel" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_templates"."channel" IS '알림 채널'`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_project_active"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_project_user"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "project_name" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "device_id"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "device_id" character varying(100)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."device_id" IS '디바이스 ID'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "platform"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "platform" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."platform" IS '플랫폼'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "inactive_reason"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "inactive_reason" character varying(1000)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."inactive_reason" IS '비활성화 사유'`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_delivery_logs_status_created_at"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "project_name" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "receiver_ref_type"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "receiver_ref_type" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."receiver_ref_type" IS '수신자 타입'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "receiver_contact"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "receiver_contact" character varying(2048)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."receiver_contact" IS '수신 주소'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "channel" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."channel" IS '알림 채널'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "status" character varying(100) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."status" IS '발송 상태'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "provider_message_id"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "provider_message_id" character varying(100)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."provider_message_id" IS '외부 provider 메시지 ID'`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_logs_project_name_created_at"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_logs_channel_created_at"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_logs_status_created_at"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "project_name" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "sender_ref_type"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "sender_ref_type" character varying(100)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."sender_ref_type" IS '발신 주체 타입'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "channel" character varying(100) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."channel" IS '알림 채널'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "link_url"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "link_url" character varying(2048)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."link_url" IS '링크 URL'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ALTER COLUMN "priority" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "status" character varying(100) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."status" IS '처리 상태'`);
        await queryRunner.query(`CREATE INDEX "idx_notification_templates_project_active" ON "notification_schema"."notification_templates" ("project_name", "is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_notification_templates_project_code_channel" ON "notification_schema"."notification_templates" ("project_name", "code", "channel") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_notification_device_tokens_project_user_device_active" ON "notification_schema"."notification_device_tokens" ("project_name", "user_ref_idx", "device_id") WHERE deleted_at IS NULL AND device_id IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_notification_device_tokens_token_active" ON "notification_schema"."notification_device_tokens" ("token") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_notification_device_tokens_project_active" ON "notification_schema"."notification_device_tokens" ("project_name", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_device_tokens_project_user" ON "notification_schema"."notification_device_tokens" ("project_name", "user_ref_idx") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_delivery_logs_status_created_at" ON "notification_schema"."notification_delivery_logs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_logs_channel_created_at" ON "notification_schema"."notification_logs" ("channel", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_logs_status_created_at" ON "notification_schema"."notification_logs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_logs_project_name_created_at" ON "notification_schema"."notification_logs" ("project_name", "created_at") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_logs_project_name_created_at"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_logs_status_created_at"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_logs_channel_created_at"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_delivery_logs_status_created_at"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_project_user"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_project_active"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_token_active"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_device_tokens_project_user_device_active"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_templates_project_code_channel"`);
        await queryRunner.query(`DROP INDEX "notification_schema"."idx_notification_templates_project_active"`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."status" IS '처리 상태'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "status" character varying(30) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ALTER COLUMN "priority" SET DEFAULT '100'`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."link_url" IS '링크 URL'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "link_url"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "link_url" text`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."channel" IS '알림 채널'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "channel" character varying(30) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."sender_ref_type" IS '발신 주체 타입'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "sender_ref_type"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "sender_ref_type" character varying(50)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_logs"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_logs" ADD "project_name" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_notification_logs_status_created_at" ON "notification_schema"."notification_logs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_logs_channel_created_at" ON "notification_schema"."notification_logs" ("channel", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_logs_project_name_created_at" ON "notification_schema"."notification_logs" ("project_name", "created_at") `);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."provider_message_id" IS '외부 provider 메시지 ID'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "provider_message_id"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "provider_message_id" character varying(255)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."status" IS '발송 상태'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "status" character varying(30) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."channel" IS '알림 채널'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "channel" character varying(30) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."receiver_contact" IS '수신 주소'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "receiver_contact"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "receiver_contact" character varying(500)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."receiver_ref_type" IS '수신자 타입'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "receiver_ref_type"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "receiver_ref_type" character varying(50) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_delivery_logs"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_delivery_logs" ADD "project_name" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_notification_delivery_logs_status_created_at" ON "notification_schema"."notification_delivery_logs" ("status", "created_at") `);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."inactive_reason" IS '비활성화 사유'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "inactive_reason"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "inactive_reason" character varying(255)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."platform" IS '플랫폼'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "platform"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "platform" character varying(30) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."device_id" IS '디바이스 ID'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "device_id"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "device_id" character varying(255)`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_device_tokens"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_device_tokens" ADD "project_name" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_notification_device_tokens_project_user" ON "notification_schema"."notification_device_tokens" ("project_name", "user_ref_idx") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_device_tokens_project_active" ON "notification_schema"."notification_device_tokens" ("project_name", "is_active") `);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_templates"."channel" IS '알림 채널'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" ADD "channel" character varying(30) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notification_schema"."notification_templates"."project_name" IS '프로젝트 이름'`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" DROP COLUMN "project_name"`);
        await queryRunner.query(`ALTER TABLE "notification_schema"."notification_templates" ADD "project_name" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_notification_templates_project_code_channel" ON "notification_schema"."notification_templates" ("project_name", "code", "channel") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_templates_project_active" ON "notification_schema"."notification_templates" ("project_name", "is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_notification_device_tokens_token" ON "notification_schema"."notification_device_tokens" ("token") `);
    }

}
